let houseSection = {
    key: {
        'K': {icon: 'back_wall_k', solid: true},
        'L': {icon: 'back_wall_l', solid: true},
        'D': {icon: 'back_wall_d', solid: true},
        'W': {icon: 'back_wall_window', solid: true},
        'B': {icon: 'stone_top_b', solid: [false, false, false, true]},
        'A': {icon: 'stone_top_a', solid: [false, true, false, false]},
        'C': {icon: 'stone_top_c', solid: [false, false, true, false]},
        'E': {icon: 'stone_top_e', solid: [false, false, true, true]},
        'F': {icon: 'stone_top_f', solid: [false, true, true, false]},
        'S': {icon: 'stairs', solid: [false, true, false, true]},
        'I': {icon: 'stone_wall_c', solid: true},
        'J': {icon: 'stone_wall_e', solid: true},
        'G': {icon: 'stone_wall_f', solid: true},
        'T': {icon: 'floor_molding_d', solid: false},
        'R': {icon: 'floor_molding_k', solid: [false, false, false, true]},
        'Q': {icon: 'floor_molding_l', solid: [false, true, false, false]},
        'X': {icon: 'floor', solid: false},
        '[': {icon: 'rug_b', solid: false, double: 'floor'},
        ']': {icon: 'rug_folded_a', solid: false, double: 'floor'},
        '%': {icon: 'stove', solid: true, double: 'floor_molding_l'},
        '*': {icon: 'workbench', solid: true, double: 'floor'},
        'O': {icon: 'pipewell', solid: false},
        'M': {icon: 'bed_d', solid: true, double: 'floor_molding_k'},
        'N': {icon: 'bed_c', solid: true, double: 'stone_top_b'},
        '=': {entity: Door, double: 'floor'},
        '#': {entity: Cactus},
        '|': {entity: Well},
    },
    section: [
        '             #    ',
        '    KWDDWL        ',
        '    MTTTT%O  #    ',
        '    NX[]X*O   #   ',
        '  | ECC=CF        ',
        '    JIISIG  #     ',
        '                  ',
    ],
}
