window.addEventListener('load', () => {
    // Load canvas and images
    game.canvas = document.getElementById('canvas')
    game.ctx = game.canvas.getContext('2d')

    game.icons.rock = document.getElementById('rock')
    game.icons.farmer = document.getElementById('farmer')
    game.icons.cliff_a = document.getElementById('cliff_a')
    game.icons.cliff_b = document.getElementById('cliff_b')
    game.icons.cliff_c = document.getElementById('cliff_c')
    game.icons.cliff_d = document.getElementById('cliff_d')
    game.icons.cliff_e = document.getElementById('cliff_e')
    game.icons.cliff_f = document.getElementById('cliff_f')
    game.icons.cliff_g = document.getElementById('cliff_g')
    game.icons.cliff_h = document.getElementById('cliff_h')
    game.icons.cliff_i = document.getElementById('cliff_i')
    game.icons.cliff_j = document.getElementById('cliff_j')
    game.icons.cliff_k = document.getElementById('cliff_k')
    game.icons.cliff_l = document.getElementById('cliff_l')
    game.icons.cliff_m = document.getElementById('cliff_m')
    game.icons.cliff_n = document.getElementById('cliff_n')
    game.icons.cliff_o = document.getElementById('cliff_o')
    game.icons.cliff_p = document.getElementById('cliff_p')
    game.icons.cliff_q = document.getElementById('cliff_q')
    game.icons.floor = document.getElementById('floor')
    game.icons.door = document.getElementById('door')
    game.icons.floor_molding_d = document.getElementById('floor_molding_d')
    game.icons.floor_molding_k = document.getElementById('floor_molding_k')
    game.icons.floor_molding_l = document.getElementById('floor_molding_l')
    game.icons.stairs = document.getElementById('stairs')
    game.icons.back_wall_d = document.getElementById('back_wall_d')
    game.icons.back_wall_k = document.getElementById('back_wall_k')
    game.icons.back_wall_l = document.getElementById('back_wall_l')
    game.icons.back_wall_window = document.getElementById('back_wall_window')
    game.icons.stone_top_a = document.getElementById('stone_top_a')
    game.icons.stone_top_b = document.getElementById('stone_top_b')
    game.icons.stone_top_c = document.getElementById('stone_top_c')
    game.icons.stone_top_e = document.getElementById('stone_top_e')
    game.icons.stone_top_f = document.getElementById('stone_top_f')
    game.icons.stone_wall_c = document.getElementById('stone_wall_c')
    game.icons.stone_wall_e = document.getElementById('stone_wall_e')
    game.icons.stone_wall_f = document.getElementById('stone_wall_f')
    game.icons.rug_b = document.getElementById('rug_b')
    game.icons.rug_folded_a = document.getElementById('rug_folded_a')
    game.icons.workbench = document.getElementById('workbench')
    game.icons.stove = document.getElementById('stove')
    game.icons.bed_d = document.getElementById('bed_d')
    game.icons.bed_c = document.getElementById('bed_c')
    game.icons.house_exterior = document.getElementById('house_exterior')
    game.icons.empty = document.getElementById('empty')

    instantiateWorld()
})
